### ISSUE TITLE
Enhancement: Sidebar Button Color

### ISSUE THREAD

**Issue by boylerplet** [furkananter/spotify-clone#1]
![image](https://user-images.githubusercontent.com/54875908/184332229-01466eba-0a9b-49e7-8f66-222caa06db59.png)
I this part, the Button _on hover_ is turning to white color, and that is good.
It would be better if you make the **selected** icon color as **_white_**, and the **not selected** ones as **_gray_** 

> [Currently all icons are gray by default]

 And for **on hover** you can add a **_scale_** animation.

**Comment by furkananter** [comment]
I checked it. I fixed the selected style to white. But if you check official version, I pulled the whole styles from original page. Colors included. Inactive buttons are gray. But tonight I'll check it again. Thank you for your comment.

**Comment by boylerplet** [comment]
@furkananter Its looking good now, also i think the svg for selected is also changing...
Here is a reference to the way it is in the **present build**
![image](https://user-images.githubusercontent.com/54875908/184367946-33f63efc-2ce4-480f-8d9d-12d7fdc8c6f8.png)

![image](https://user-images.githubusercontent.com/54875908/184368026-4b32aff0-9159-4e73-be08-1845639c55dc.png)
